require 'rake'
require 'rspec/core/rake_task'

task :serverspec => 'serverspec:all'
task :default => :serverspec

namespace :serverspec do
  targets = []
  Dir.glob('./serverspec/*').each do |dir|
    next unless File.directory?(dir)
    target = File.basename(dir)
    targets << target
  end

  task :all => targets

  targets.each do |target|
    desc "Run serverspec tests on #{target}"
    RSpec::Core::RakeTask.new("#{target.to_sym}") do |t|
      t.pattern = "serverspec/#{target}/*_spec.rb"
      t.rspec_opts = '--color --format documentation'
      t.verbose = true
    end
  end
end
